version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    command:
      -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    env_file:
      - .env-non-dev
    container_name: redis
    command: --port 5370
    expose:
      - 5370


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
