"""Fix component associations

Revision ID: b9fe257674fc
Revises: 5834001bf7a0
Create Date: 2023-06-24 02:30:12.588996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fe257674fc'
down_revision = '5834001bf7a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
