"""Data now not nullable

Revision ID: cfd16fa7dcc0
Revises: 21efe125fb50
Create Date: 2023-06-27 02:17:05.655475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd16fa7dcc0'
down_revision = '21efe125fb50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
