"""Add component associations

Revision ID: 5834001bf7a0
Revises: 031aa5c0d19d
Create Date: 2023-06-23 22:43:29.799494

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5834001bf7a0'
down_revision = '031aa5c0d19d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_association',
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.Column('child_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['child_id'], ['component.id'], ),
                    sa.ForeignKeyConstraint(['parent_id'], ['component.id'], ),
                    sa.PrimaryKeyConstraint('parent_id', 'child_id')
                    )
    op.drop_table('edge_component_to_component')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
