"""Add materials

Revision ID: 167ed0768707
Revises: cfd16fa7dcc0
Create Date: 2023-06-27 22:15:35.937313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167ed0768707'
down_revision = 'cfd16fa7dcc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
