"""Update data

Revision ID: 031aa5c0d19d
Revises: 7bb3d8ad6546
Create Date: 2023-06-23 21:24:26.736998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031aa5c0d19d'
down_revision = '7bb3d8ad6546'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('component', 'data')
    # ### end Alembic commands ###
