"""Add system table

Revision ID: 21efe125fb50
Revises: b9fe257674fc
Create Date: 2023-06-25 02:59:54.909039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21efe125fb50'
down_revision = 'b9fe257674fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    # ### end Alembic commands ###
